PROFILE_URL_NAME = 'posts:profile'
POST_CREATE_URL_NAME = 'posts:post_create'
POST_EDIT_URL_NAME = 'posts:post_edit'
INDEX_URL_NAME = 'posts:index'
GROUP_LIST_URL_NAME = 'posts:group_list'
POST_DETAIL_URL_NAME = 'posts:post_detail'

AUTHOR_USERNAME = 'Nikolo'
USER_USERNAME = 'TestUser'

GROUP_TITLE = 'Тестовая группа'
GROUP_SLUG = 'test-slug'
GROUP_DESCRIPTION = 'Тестовое описание'
POST_TEXT = 'Тестовый текст'

INDEX_TEMPLATE = 'posts/index.html'
GROUP_LIST_TEMPLATE = 'posts/group_list.html'
PROFILE_TEMPLATE = 'posts/profile.html'
POST_DETAIL_TEMPLATE = 'posts/post_detail.html'
CREATE_POST_TEMPLATE = 'posts/create_post.html'
